/* This file was automatically generated by CasADi 3.6.4.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) wr_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s1[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s2[12] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s3[7] = {3, 1, 0, 3, 0, 1, 2};

/* wr_expl_vde_adj:(i0[2],i1[2],i2,i3[8])->(o0[3]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real *w0=w+2, *w1=w+4, *w2=w+8, *w3=w+12, w4, w5, w6;
  /* #0: @0 = zeros(2x1) */
  casadi_clear(w0, 2);
  /* #1: @1 = input[3][2] */
  casadi_copy(arg[3] ? arg[3]+4 : 0, 4, w1);
  /* #2: @2 = @1' */
  for (i=0, rr=w2, cs=w1; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #3: @3 = input[1][0] */
  casadi_copy(arg[1], 2, w3);
  /* #4: @0 = mac(@2,@3,@0) */
  for (i=0, rr=w0; i<1; ++i) for (j=0; j<2; ++j, ++rr) for (k=0, ss=w2+j, tt=w3+i*2; k<2; ++k) *rr += ss[k*2]**tt++;
  /* #5: {@4, @5} = vertsplit(@0) */
  w4 = w0[0];
  w5 = w0[1];
  /* #6: output[0][0] = @4 */
  if (res[0]) res[0][0] = w4;
  /* #7: {@4, @6} = vertsplit(@3) */
  w4 = w3[0];
  w6 = w3[1];
  /* #8: @5 = (@5+@4) */
  w5 += w4;
  /* #9: output[0][1] = @5 */
  if (res[0]) res[0][1] = w5;
  /* #10: output[0][2] = @6 */
  if (res[0]) res[0][2] = w6;
  return 0;
}

CASADI_SYMBOL_EXPORT int wr_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int wr_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int wr_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void wr_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int wr_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void wr_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void wr_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void wr_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int wr_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int wr_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real wr_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* wr_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* wr_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* wr_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* wr_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int wr_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 17;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
